import React, { useEffect, useState } from "react";
import Window from "components/Window/WindowBox";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";
import LandingScreen from "components/LandingScreen/LandingScreen";
import { useOnIdle } from "hooks/idleTimerHooks";
import Screensaver from "components/Overlays/Screensaver";

const Table: NextPage = () => {
  // //Screensaver
  // const showScreensaver = () => {
  //   setShowSS(false);
  //   console.log("Showing ss");
  // };
  // const hideScreensaver = () => {
  //   setShowSS(true);
  //   console.log("hiding ss");
  // };

  // useOnIdle({
  //   debounce: 500,
  //   idleTimeout: 10000,
  //   onIdle: hideScreensaver,
  //   onAction: showScreensaver,
  //   events: [
  //     "mousemove",
  //     "keydown",
  //     "wheel",
  //     "DOMMouseScroll",
  //     "mouseWheel",
  //     "mousedown",
  //     "visibilitychange",
  //     "touchmove",
  //   ],
  // });

  // const [showSS, setShowSS] = useState(false);
  // /////

  return (
    <React.StrictMode>
      <Head>
        <title>table</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/graphics/menu_assets/image0.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image1.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image2.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image3.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image4.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image5.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image6.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image7.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image8.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image9.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image10.png"
          as="image"
          type="image/png"
        />

        <link
          rel="preload"
          href="/graphics/menu_assets/image11.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image12.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image13.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image14.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image15.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image16.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image17.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image18.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image19.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image20.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/graphics/menu_assets/image21.png"
          as="image"
          type="image/png"
        />
      </Head>

      <div
        style={{
          background: "radial-gradient(ellipse at bottom, #1b2735 0%, #090a0f 100%)",
          width: "100%",
          height: "100%",
          position: "absolute",
          inset: "0",
        }}
      ></div>
      <LandingScreen />
      {/* <Screensaver show={showSS} /> */}
    </React.StrictMode>
  );
};

export default Table;
