import Head from "next/head";

export default function PreloadHead() {
  return (
    <Head>
      <title>table</title>
      <link
        rel="preload"
        href="/graphics/menu_assets/image0.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image1.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image2.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image3.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image4.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image5.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image6.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image7.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image8.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image9.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image10.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image11.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image12.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image13.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image14.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image15.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image16.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image17.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image18.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image19.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image20.png"
        as="image"
        type="image/png"
      />
      <link
        rel="preload"
        href="/graphics/menu_assets/image21.png"
        as="image"
        type="image/png"
      />
      <link rel="preload" href="/gallery/new/Video1.mp4" as="video" type="video/mp4" />
    </Head>
  );
}
